query getAttendanceByUsername($day: LocalDate!, $username: String!) {
  attendanceByUserName(day: $day, username: $username) {
    clockIn
    clockOut
    totalHoursWorked
  }
}


query getAttendanceByUserId($userid : Int!, $startdate: LocalDate!,$stopdate: LocalDate!) {
  attendanceByUserId(userId: $userid, startDate: $startdate, stopDate:$stopdate) {
    clockIn 
    clockOut 
    currentDate 
  }
}
