# mutation createNewRequest($userId: Int!, $reason: String!) {
#   createRequestLog(userid: $userId, reason: $reason)
# }

query getRequestLogsByUserId($userId: Int!) {
  requestLogsByUserId(id: $userId) {
    id
    reason
    appUserId
    currentDate
  }
}
